services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    env_file:
        - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    networks:
      - nest-app
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/usr/src/app
    # Run in dev Mode: npm run start:dev
    ports:
      - 3000:3000
      - 5555:5555
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - '5432:5432'
    networks:
      - nest-app
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

volumes:
  docker-nest-postgres:
  redis:
    driver: local

networks:
  # Separa as redes de Banco de dados das demais
  nest-app: {}